# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Roland Coeurjoly
email: rolandcoeurjoly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rcoeurjoly.github.io" # the base hostname & protocol for your site
github_username:  RCoeurjoly

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://rcoeurjoly.github.io"
baseurl: ""

projects:
  Attics:
    url: "attics"
    description: "iOS App and REST API that lets users stream thousands of live concert recordings"
  SRCT Schedules:
    url: "schedules"
    description: "Web application built with Mason SRCT that helps students create their course schedules."

# Third-party services
# just leave someone empty to disable it
# google_analytics:
disqus_shortname:
collections:
  - notes
# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
