#+OPTIONS: toc:nil num:nil


#+BEGIN_EXPORT html
---
layout: post
title: The slippery slope of Chinese
subtitle: 
tags: [Chinese, readability, language learning]
category: blog
---
#+END_EXPORT

So why should we care about the rate at which a certain author introduces new Chinese characters in a book? Because of mental bandwidth.

I read this idea in a fantastic book called Scarcity, by Sendhil Mullainathan and Eldar Shafir.

In this post I’m going to try to expand their idea so that it applies to vocabularies.

** Standing on the shoulders of giants
I am basing this post on the ideas put forward by the extensive reading researchers.

My simplified understanding of extensive reading is the following: if you understand most of the text, you can learn new words by context.

What does “most of the text” mean? Roughly 99%.

How fast can you learn new words? You can learn a new word when you encounter it 7 times in different, comprehensible contexts.

The comprehension constraint is very strict: if the unknown words reach 3 per cent, you can no longer understand the text.

So, a book that introduces vocabulary more slowly is less demanding on the mental bandwidth of the reader, whereas a difficult book does not.

Questions that remain unanswered: can you show me the slope of a book?

I will refine this posts with references and graphs in the future.

#+BEGIN_EXPORT html
<!--description-->
#+END_EXPORT
